export default {
  PURCHASE_VALIDATE: 'PURCHASE_VALIDATE',
  PURCHASE_LIST_FUNDERS: 'PURCHASE_LIST_FUNDERS',
  PURCHASE_SELECTED_FUNDER: 'PURCHASE_SELECTED_FUNDER',
  PURCHASE_FAILED: 'PURCHASE_FAILED'
};