export default {
  PURCHASE_VALIDATE: 'PURCHASE_VALIDATE',
  PURCHASE_CODE_VALIDATED: 'PURCHASE_CODE_VALIDATED',
  PRUCHASE_CODE_INVALID: 'PRUCHASE_CODE_INVALID',
  PURCHASE_LIST_FUNDERS: 'PURCHASE_LIST_FUNDERS',
  PURCHASE_SELECTED_FUNDER: 'PURCHASE_SELECTED_FUNDER',
  PURCHASE_FAILED: 'PURCHASE_FAILED'
};