// export types
export default {
  SIGN_UP_PROFILE: 'SIGN_UP_PROFILE',
  SIGN_UP_ADDRESS: 'SIGN_UP_ADDRESS',
  SIGN_IN_USER: 'SIGN_IN_USER',
  SIGN_FAILED: 'SIGN_FAILED',
  SIGN_VALIDATE: 'SIGN_VALIDATE',
  SIGN_IN_PROFILE: 'SIGN_IN_PROFILE',
};